name: 'Update Check'
description: 'See if an image (dnf-based only) needs to be rebuilt or not'

inputs:
  imageref:
    description: 'Image to check for updates'
    required: true
  baseref:
    description: 'Base image to check for updates'
    required: true

outputs:
  rebuild-needed:
    description: "If the image needs to be rebuilt"
    value: ${{ steps.results.outputs.rebuild-needed }}


# 'dnf check-update'
# exit codes:
#   0 - no updates
#   100 - updates available
#   125 - image not found
#   127 - dnf command not found
runs:
  using: "composite"
  steps:
    - name: Check for Updates
      id: check_update
      shell: bash
      run: |
        res=0
        podman run --quiet --rm ${{ inputs.imageref }} dnf check-update || res=$?
        echo "res=${res}" >> "$GITHUB_OUTPUT"
        echo "Exit code: '$res'"

    - name: Check base for Updates
      id: check_base
      if: ${{ steps.check_update.outputs.res == '100' }}
      shell: bash
      run: |
        res=0
        podman run --quiet --rm ${{ inputs.baseref }} dnf check-update || res=$?
        echo "res=${res}" >> "$GITHUB_OUTPUT"
        echo "Exit code: '$res'"

    - name: Results
      id: results
      shell: bash
      run: |
        if [ "${{ needs.check_update.outputs.res }}" = "0" ]; then
          echo "Image does not need rebuild"
          echo "rebuild-needed=false" >> "$GITHUB_OUTPUT"
        elif [ "${{ needs.check_update.outputs.res }}" = "125" ]; then
          echo "Image not found, build it"
          echo "rebuild-needed=true" >> "$GITHUB_OUTPUT"
        elif [ "${{ needs.check_update.outputs.res }}" = "100" ]; then
          if [ "${{ needs.check_base.outputs.res }}" = "0" ]; then
            echo "Updates available for ${{ inputs.imageref }} and base image is up to date"
            echo "rebuild-needed=true" >> "$GITHUB_OUTPUT"
          else
            echo "Updates available for ${{ inputs.imageref }}, but base image needs to be rebuilt first"
            echo "rebuild-needed=false" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "rebuild-needed=false" >> "$GITHUB_OUTPUT"
        fi
